name: hello-word
description: >
  Check if a project / analysis passed the Quality Gate check
branding:
  icon: check
  color: green
runs:
  using: "composite"
  steps:
    #- run: $GITHUB_ACTION_PATH/script/test.sh 
    - run: |
             echo "username:${{inputs.username}}"
             echo "cat 1.txt"
             cat $GITHUB_ACTION_PATH/1.txt
      shell: bash
inputs:
  username:
    description: user_name
    required: false
    default: "张三"
