name: 'Dependency Review'
on: push

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        run: |
         echo '123';
         exit 100
        
