# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

#     - name: Build with Maven
#       run: mvn -B package --file pom.xml -Dmaven.test.skip=true 
    - name: test
      run: |
            mkdir test
            echo "123" > test/1.txt
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: test
        remote: /opt/ssh_mkdir
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
    - name: dddd
      uses: appleboy/ssh-action@master
      with:
        host: 121.37.169.185
        username: root
        password: Zhuwenhao123456
        port: 22
        script: |
           echo 123
           ls /opt -al
    - name: deploy
      run: |
        ls -al
        echo "-----------------"

