name: Sub Workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true  
env:
 uname: ${{ inputs.username }}
 
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: 
           echo '${{github.workspace}}'           
           echo '传入参数变成环境变量${{env.uname}}'
           echo "token is ${{secrets.token}}"
      - uses: actions/checkout@v2
        with:
         fetch-depth: 0    
      - uses:  bone7System/test_actions/.github/actions/hello-word-action@main
        with:
         username : "${{ inputs.username }}"        
