name: Sub Workflow

on: 
  workflow_call:
    inputs:
      release_type:
        type: string
        required: true
    secrets:
        token:
          required: false      
 
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Release Type: ${{ inputs.release_type }}"
          echo "token is ${{secrets.token}}"
