name: xxxx
on: 
  push:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          java -version
          echo -e "\033[31m 红色字 \033[0m"
          echo project_name=$(basename ${{ github.repository }}) >> $GITHUB_ENV
          echo $project_name
  my-job2:
    runs-on: ubuntu-latest
    steps:
      - name: job2
        run: |
           echo $project_name
           echo ${{env.project_name}}
  call-sub-workflow:
    uses: bone7System/test_actions/.github/workflows/sub_workflow.yml@main
    with:
      username : 'xxxxx'
    secrets:      
      token: ${{secrets.SONARQUBE_HOST}}        


       
    
