# name: xxxx
# on: 
#   push:

# jobs:
#   my-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print Inputs
#         id: a 
#         run: |  
#           java -version
#           echo -e "\033[31m 红色字 \033[0m"
#       - uses: actions/checkout@v2
#         with:
#          fetch-depth: 0    
#       - uses:  ./.github/actions/hello-word-action
#         id: abc
#         with:
#          username : 'xxxx草草草草x'
#       - name: shuchu 
#         run: |
#               echo "输出内容：${{steps.abc.outputs.my_output_name}}"
        
#   call-sub-workflow:
#     uses: bone7System/test_actions/.github/workflows/sub_workflow.yml@main
#     with:
#       username : 'hjkl'
#     secrets:      
#       token: 'rrrrrr'    
      
# name: Context testing
# on: push

# env:
#  myname: 123

# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Dump GitHub context
#         id: step1
#         run: | 
#           echo ${{ env.myname }}
#          # echo "::set-output name=project_name::hello"
#     outputs:
#      project_name: airflow
   
    
#   job2:
#    if: ${{ needs.job1.outputs.project_name == 'airflow2' }}
#    runs-on: ubuntu-latest
#    needs: job1
#    steps:
#      - name: Dump GitHub context
#        id: j1
#        run: echo ${{ env.myname }}     

# jobs:
#   dump_contexts_to_log:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Dump GitHub context
#         id: github_context_step
#         run: |
#            echo 1233
#              string='${{ github.event.head_commit.message }}'
#            array=(${string//\n/ })  
#            echo "array[0]=${array[0]}"
#            for var in ${array[@]}
#             do
#                echo $var
#             done
#            echo 'end'
#            echo -e '${{ github.event.head_commit.message }}'
           
#             commit_message='${{ github.event.head_commit.message }}'
#             echo '--------------------------------'
#             echo $commit_message
#             echo '--------------------------------'
#             title="${commit_message%\n\n*}"
#              echo '#################################￥  '
#              echo "title:$title"
#              echo '################################# '
#                 echo '--------------------------------'
#              echo '################################# '
#               tag_version="v2222_${title}_$(date '+%Y%m%d%H%M%S')"
#               echo "$tag_version"
#               echo '#################################'
#            echo  "${{ github.sha }}"

# on: issue_comment

# jobs:
#   pr_commented:
#     # This job only runs for pull request comments
#     name: PR comment
#     if: ${{ github.event.issue.pull_request }}
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo '${{ toJSON(github.event) }}'
#           echo A comment on PR $NUMBER
#         env:
#           NUMBER: ${{ github.event.issue.number }}

#   issue_commented:
#     # This job only runs for issue comments
#     name: Issue comment
#     if: ${{ !github.event.issue.pull_request }}
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo A comment on issue $NUMBER
#         env:
#           NUMBER: ${{ github.event.issue.number }}



# on:
#   pull_request:
  

  
# jobs:
#   dump_contexts_to_log:
#     runs-on: ubuntu-latest
#     steps:
#          - name: Checkout github repo (+ download lfs dependencies)
#            uses: actions/checkout@v2
#    #         with:
#    #          ref: ${{ github.event.pull_request.head.sha }}
#            with:
#                 fetch-depth: 2
#          - name: Dump GitHub context
#            id: github_context_step
#            run: |
#                echo -e '${{ github.event.head_commit.message }}'
#                echo 'cat test.txt'
#                cat test.txt
#          - name: Dump GitHub context
#            run: echo '${{ toJSON(github) }}'
#          - name: Dump job context
#            run: echo '${{ toJSON(job) }}'
#          - name: Dump steps context
#            run: echo '${{ toJSON(steps) }}'
#          - name: Dump runner context
#            run: echo '${{ toJSON(runner) }}'
#          - name: Dump strategy context
#            run: echo '${{ toJSON(strategy) }}'
#          - name: Dump matrix context
#            run: echo '${{ toJSON(matrix) }}'


# name: Dependabot Pull Request
# on:
#   create


# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Adding markdown
#       run: echo '### Hello world ! :rocket:' >> $GITHUB_STEP_SUMMARY


name:  create
on:
  create


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Adding markdown
      run:  echo '### Hello 1 ! :rocket:' >> $GITHUB_STEP_SUMMARY
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy markdown
      run:  echo '### Hello 2 ! :rocket:' >> $GITHUB_STEP_SUMMARY
