# name: xxxx
# on: 
#   push:

# jobs:
#   my-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print Inputs
#         id: a
#         run: |
#           java -version
#           echo -e "\033[31m 红色字 \033[0m"
#           echo project_name=$(basename ${{ github.repository }}) >> $GITHUB_ENV
#           echo $project_name
#   call-sub-workflow:
#     uses: bone7System/test_actions/.github/workflows/sub_workflow.yml@main
#     with:
#       username : 'xxxxx'
#     secrets:      
#       token: ${{secrets.SONARQUBE_HOST}}

name: Context testing
on: push

env:
 myname: 123

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: step1
        run: | 
          echo ${{ env.myname }}
          echo "::set-output name=project_name::hello"
    outputs:
     project_name: airflow
   
    
  job2:
   if: ${{ needs.job1.outputs.project_name == 'airflow' }}
   runs-on: ubuntu-latest
   needs: job1
   steps:
     - name: Dump GitHub context
       id: j1
       run: echo ${{ env.myname }}     

     





       
    
