# name: xxxx
# on: 
#   push:

# jobs:
#   my-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print Inputs
#         id: a 
#         run: |  
#           java -version
#           echo -e "\033[31m 红色字 \033[0m"
#           echo project_name=$(basename ${{ github.repository }}) >> $GITHUB_ENV
#           echo $project_name
#   call-sub-workflow:
#     uses: bone7System/test_actions/.github/workflows/sub_workflow.yml@main
#     with:
#       username : 'xxxxx'
#     secrets:      
#       token: ${{secrets.SONARQUBE_HOST}}

name: Context testing
on: push

env:
 myname: 123

# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Dump GitHub context
#         id: step1
#         run: | 
#           echo ${{ env.myname }}
#          # echo "::set-output name=project_name::hello"
#     outputs:
#      project_name: airflow
   
    
#   job2:
#    if: ${{ needs.job1.outputs.project_name == 'airflow2' }}
#    runs-on: ubuntu-latest
#    needs: job1
#    steps:
#      - name: Dump GitHub context
#        id: j1
#        run: echo ${{ env.myname }}     

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: |
           echo 1233
           echo -e '${{ github.event.head_commit.message }}'
            commit_message='${{ github.event.head_commit.message }}'
            echo '--------------------------------'
            echo $commit_message
            echo '--------------------------------'
            title="${commit_message% *}"
             echo '#################################￥  '
             echo "title:$title"
             echo '################################# '
                echo '--------------------------------'
             echo '################################# '
              tag_version="v2222_${title}_$(date '+%Y%m%d%H%M%S')"
              echo "$tag_version"
              echo '#################################'
           echo  "${{ github.sha }}"





       
    
