# name: xxxx
# on: 
#   push:

# jobs:
#   my-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print Inputs
#         id: a
#         run: |
#           java -version
#           echo -e "\033[31m 红色字 \033[0m"
#           echo project_name=$(basename ${{ github.repository }}) >> $GITHUB_ENV
#           echo $project_name
#   call-sub-workflow:
#     uses: bone7System/test_actions/.github/workflows/sub_workflow.yml@main
#     with:
#       username : 'xxxxx'
#     secrets:      
#       token: ${{secrets.SONARQUBE_HOST}}

name: Context testing
on: push

env:
 myname: 123

jobs:
  dump_contexts_to_log:
    if: ${{ env.myname }} == 123
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo ${{ env.myname }}
     





       
    
