name: xxxx
on: 
  push:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        id: a
        run: |
          java -version
          echo -e "\033[31m 红色字 \033[0m"
          echo project_name=$(basename ${{ github.repository }}) >> $GITHUB_ENV
          echo $project_name
  my-job2:
    runs-on: ubuntu-latest
    needs: [ my-job ]
    steps:
      - name: Print Inputs
        id: a
        run: |
          echo '::set-output name=SELECTED_COLOR::green'
      - name: job2
        run: |
           echo ${{steps.a.outputs.SELECTED_COLOR}}
           echo ${{env.project_name}}
  call-sub-workflow:
    uses: bone7System/test_actions/.github/workflows/sub_workflow.yml@main
    with:
      username : 'xxxxx'
    secrets:      
      token: ${{secrets.SONARQUBE_HOST}}        


       
    
