name: xxxx
on: 
  workflow_dispatch:

jobs:
  call-sub-workflow:
    uses: bone7System/test_actions/.github/workflows/sub_workflow.yml@main
    with:
      release_type: ${{ github.event.inputs.release_type }}
