name: xxxx
on: 
  push:

jobs:
  call-sub-workflow:
    uses: bone7System/test_actions/.github/workflows/sub_workflow.yml@main
    with:
      release_type: 'xxxxx'
      token: ${{secrets.SONARQUBE_HOST}}
