name: 'Merge branch'
on:
  push

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          ref: 'master'

      - name: Git merge operation
        uses: alexrogalskiy/github-action-git-operation@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: 'merge-fast-forward'
          sourceBranch: 'main'
          targetBranch: 'merge-test'         



     
    
