env:
  project_type: 111test_actions111
name: Context testing
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: project name
        run: |
          echo  ${##*/${{ github.repository }} } '----项目-'
          echo $(basename ${{ github.repository }}) ${{ env.project_type }} '----项目2-'
      - name: 判断怎么发布
        if: $(basename ${{ github.repository }}) == 'test_actions'
        run: 
          echo '发布test_ations'  
         
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
