name: 'Merge branch'
on:
  push

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Merge main -> merge-test
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ steps.extract_branch.outputs.branch }}
          target_branch: merge-test
          github_token: ${{ github.token }}
       



     
    
