name: 'Merge branch'
on:
  push

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> merge-test
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: merge-test
          github_token: ${{ github.token }}
       



     
    
